### ISSUE TITLE
PodLogCollector: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2077

### ISSUE THREAD

**Issue by sergiitk** [grpc/psm-interop#102]
In some cases, restart_stream leads to `UnicodeDecodeError`:

```py
Exception in thread pod-log-psm-grpc-server-65dbd75668-qw72g:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/tmp/work/psm-interop/framework/infrastructure/k8s_internal/k8s_log_collector.py", line 82, in run
    self._stream_log()
  File "/tmp/work/psm-interop/framework/infrastructure/k8s_internal/k8s_log_collector.py", line 110, in _stream_log
    self._restart_stream()
  File "/tmp/work/psm-interop/framework/infrastructure/k8s_internal/k8s_log_collector.py", line 136, in _restart_stream
    for msg in self._watcher.stream(
  File "/tmp/work/psm-interop/venv/lib/python3.9/site-packages/kubernetes/watch/watch.py", line 165, in stream
    for line in iter_resp_lines(resp):
  File "/tmp/work/psm-interop/venv/lib/python3.9/site-packages/kubernetes/watch/watch.py", line 58, in iter_resp_lines
    seg = seg.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2077: invalid start byte
```

**Comment by sergiitk** [comment]
Looks like this breaks log collection in staging, example: fusion2/bb7a5794-f3fe-3fbb-b593-75aa66130959. Need to check prod as well. We should fix it ASAP.

FYI @gnossen @XuanWang-Amos

**Comment by sergiitk** [comment]
Looks like this was fixed in https://github.com/kubernetes-client/python/pull/2100 and released in https://github.com/kubernetes-client/python/releases/tag/v30.1.0. We need to update to this version, currently we use 27.2.0 https://github.com/grpc/psm-interop/blob/657acc2637b34ea167c5289762f02be07dae7042/requirements.lock#L11

**Comment by sergiitk** [comment]
Notes:
- Prod runs affected as well: https://source.cloud.google.com/results/invocations/4c6f7eb8-3542-418f-ba78-ad8c4e685331
- It appears that the logging change that triggered this edge case was introduced in core v1.65.x. This means 100% of runs of cpp and python >= v1.65.x (including master) are affected
- As long as updating the k8s py client fixes the issue, it shouldn't matter what specific change in core started triggering the edge case
